const types = {
  INITIALIZE_GRID: 'INITIALIZE_GRID',
  INITIATE_MARK_GRID: 'INITIATE_MARK_GRID',
  MARK_GRID: 'MARK_GRID',
  SET_GAME_TYPE: 'SET_GAME_TYPE',
  START_LOCAL_GAME: 'START_LOCAL_GAME',
  HOST_SESSION: 'HOST_SESSION',
  SHOW_JOIN_SESSION_FORM: 'SHOW_JOIN_SESSION_FORM',
  JOIN_SESSION: 'JOIN_SESSION',
  WRONG_SESSION: 'WRONG_SESSION',
  SUBMIT_SESSION: 'SUBMIT_SESSION',
  TURN_SWITCH: 'TURN_SWITCH',
  INITIATE_QUIT: 'INITIATE_QUIT',
  INITIATE_RESTART: 'INITIATE_RESTART',
  QUIT: 'QUIT',
  RESTART: 'RESTART',
  FINISHED: 'FINISHED'
};

export default types;